import { Inter } from 'next/font/google'
import './globals.css'
import * as React from 'react'
import Providers from './generalComponents/providers'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Life V',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          {children}
        </Providers>
        
      </body>
    </html>
  )
}
